"use strict";
exports.__esModule = true;
var core_1 = require("@dags/core");
var dag = new core_1.Dag(new core_1.UUID());
var parent = dag.newNode();
var child = dag.newNode();
console.log(dag.getNodes().size);
console.log(dag.getChildren(parent).size);
console.log(dag.getParents(child).size);
dag.setParenthood(child, parent);
console.log(dag.getChildren(parent).size);
console.log(dag.getParents(child).size);
dag.removeParenthood(child, parent);
console.log(dag.getChildren(parent).size);
console.log(dag.getParents(child).size);
